export enum UiColor {
  BrandDark = 'brand-dark',
  BrandBase = 'brand-base',
  Gray800 = 'gray-800',
  Gray700 = 'gray-700',
  Gray600 = 'gray-600',
  Gray500 = 'gray-500',
  Gray400 = 'gray-400',
  Gray300 = 'gray-300',
  Gray200 = 'gray-200',
  Gray100 = 'gray-100',
  Black = 'black',
  White = 'white',
  Danger = 'danger',
  Success = 'success',
  BlueDark = 'blue-dark',
  BlueBase = 'blue-base',
  BlueLight = 'blue-light',
  PurpleDark = 'purple-dark',
  PurpleBase = 'purple-base',
  PurpleLight = 'purple-light',
  PinkDark = 'pink-dark',
  PinkBase = 'pink-base',
  PinkLight = 'pink-light',
  RedDark = 'red-dark',
  RedBase = 'red-base',
  RedLight = 'red-light',
  OrangeDark = 'orange-dark',
  OrangeBase = 'orange-base',
  OrangeLight = 'orange-light',
  YellowDark = 'yellow-dark',
  YellowBase = 'yellow-base',
  YellowLight = 'yellow-light',
  GreenDark = 'green-dark',
  GreenBase = 'green-base',
  GreenLight = 'green-light'
}

export type UiColorType = UiColor

export const UI_COLORS: UiColorType[] = [
  UiColor.BrandDark,
  UiColor.BrandBase,
  UiColor.Gray800,
  UiColor.Gray700,
  UiColor.Gray600,
  UiColor.Gray500,
  UiColor.Gray400,
  UiColor.Gray300,
  UiColor.Gray200,
  UiColor.Gray100,
  UiColor.Black,
  UiColor.White,
  UiColor.Danger,
  UiColor.Success,
  UiColor.BlueDark,
  UiColor.BlueBase,
  UiColor.BlueLight,
  UiColor.PurpleDark,
  UiColor.PurpleBase,
  UiColor.PurpleLight,
  UiColor.PinkDark,
  UiColor.PinkBase,
  UiColor.PinkLight,
  UiColor.RedDark,
  UiColor.RedBase,
  UiColor.RedLight,
  UiColor.OrangeDark,
  UiColor.OrangeBase,
  UiColor.OrangeLight,
  UiColor.YellowDark,
  UiColor.YellowBase,
  UiColor.YellowLight,
  UiColor.GreenDark,
  UiColor.GreenBase,
  UiColor.GreenLight
]

export function toCssColorVar(color: UiColorType) {
  return `var(--${color})`
}
