import type { LucideIcon } from 'lucide-react'
import {
  ArrowUpDown,
  BaggageClaim,
  BookOpen,
  BriefcaseBusiness,
  CarFront,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleArrowDown,
  CircleArrowUp,
  Dumbbell,
  EyeOff,
  Gift,
  HeartPulse,
  House,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Mailbox,
  PawPrint,
  PiggyBank,
  Plus,
  ReceiptText,
  Search,
  ShoppingCart,
  Square,
  SquareCheck,
  SquarePen,
  Tag,
  Ticket,
  ToolCase,
  Trash,
  User,
  UserPlus,
  Utensils,
  Wallet,
  X
} from 'lucide-react'

export enum UiIcon {
  ArrowUpDown = 'arrow-up-down',
  BaggageClaim = 'baggage-claim',
  BookOpen = 'book-open',
  BriefcaseBusiness = 'briefcase-business',
  CarFront = 'car-front',
  ChevronDown = 'chevron-down',
  ChevronLeft = 'chevron-left',
  ChevronRight = 'chevron-right',
  CircleArrowDown = 'circle-arrow-down',
  CircleArrowUp = 'circle-arrow-up',
  Dumbbell = 'dumbbell',
  EyeOff = 'eye-off',
  Gift = 'gift',
  HeartPulse = 'heart-pulse',
  House = 'house',
  Lock = 'lock',
  LogIn = 'log-in',
  LogOut = 'log-out',
  Mail = 'mail',
  Mailbox = 'mailbox',
  PawPrint = 'paw-print',
  PiggyBank = 'piggy-bank',
  Plus = 'plus',
  ReceiptText = 'receipt-text',
  Search = 'search',
  ShoppingCart = 'shopping-cart',
  Square = 'square',
  SquareCheck = 'square-check',
  SquarePen = 'square-pen',
  Tag = 'tag',
  Ticket = 'ticket',
  ToolCase = 'tool-case',
  Trash = 'trash',
  User = 'user',
  UserPlus = 'user-plus',
  Utensils = 'utensils',
  Wallet = 'wallet',
  X = 'x'
}

export type UiIconType = UiIcon

export const UI_ICON_COMPONENTS: Record<UiIconType, LucideIcon> = {
  [UiIcon.ArrowUpDown]: ArrowUpDown,
  [UiIcon.BaggageClaim]: BaggageClaim,
  [UiIcon.BookOpen]: BookOpen,
  [UiIcon.BriefcaseBusiness]: BriefcaseBusiness,
  [UiIcon.CarFront]: CarFront,
  [UiIcon.ChevronDown]: ChevronDown,
  [UiIcon.ChevronLeft]: ChevronLeft,
  [UiIcon.ChevronRight]: ChevronRight,
  [UiIcon.CircleArrowDown]: CircleArrowDown,
  [UiIcon.CircleArrowUp]: CircleArrowUp,
  [UiIcon.Dumbbell]: Dumbbell,
  [UiIcon.EyeOff]: EyeOff,
  [UiIcon.Gift]: Gift,
  [UiIcon.HeartPulse]: HeartPulse,
  [UiIcon.House]: House,
  [UiIcon.Lock]: Lock,
  [UiIcon.LogIn]: LogIn,
  [UiIcon.LogOut]: LogOut,
  [UiIcon.Mail]: Mail,
  [UiIcon.Mailbox]: Mailbox,
  [UiIcon.PawPrint]: PawPrint,
  [UiIcon.PiggyBank]: PiggyBank,
  [UiIcon.Plus]: Plus,
  [UiIcon.ReceiptText]: ReceiptText,
  [UiIcon.Search]: Search,
  [UiIcon.ShoppingCart]: ShoppingCart,
  [UiIcon.Square]: Square,
  [UiIcon.SquareCheck]: SquareCheck,
  [UiIcon.SquarePen]: SquarePen,
  [UiIcon.Tag]: Tag,
  [UiIcon.Ticket]: Ticket,
  [UiIcon.ToolCase]: ToolCase,
  [UiIcon.Trash]: Trash,
  [UiIcon.User]: User,
  [UiIcon.UserPlus]: UserPlus,
  [UiIcon.Utensils]: Utensils,
  [UiIcon.Wallet]: Wallet,
  [UiIcon.X]: X
}

export const UI_ICON_OPTIONS: UiIconType[] = Object.values(UiIcon)
